# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/UART/UART/UART.cache/wt [current_project]
set_property parent.project_path /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/UART/UART/UART.xpr [current_project]
set_property default_lib lib_VHDL [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/UART/UART/UART.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library lib_VHDL {
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/add_Round_Key.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/UART/ascii_to_hexa.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/present_library.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/block_Cypher.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/UART/emiss_rs232.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/fsm_present_MEM.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/UART/fsm_write.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/key_Schedule.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/key_Schedule_128.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/memory.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/p_Layer.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/p_Layer_Inv.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/present.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/UART/recep_rs232.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/register_80_Bits.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/register_WIDTH_Bits.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/s_Box_4_Bits.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/s_Box_4x16_Bits.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/s_Box_Inv_4_Bits.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/s_Box_Inv_4x16_Bits.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/UART/shift_register.vhd
  /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/UART/emiss_recep_rs232_bram.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/UART/zedb_emiss_recep_rs232_bram.xdc
set_property used_in_implementation false [get_files /tp/xph2sei/xph2sei401/ProjetNumeriquePhelma/vhd/UART/zedb_emiss_recep_rs232_bram.xdc]


synth_design -top emiss_recep_rs232_bram -part xc7z020clg484-1


write_checkpoint -force -noxdef emiss_recep_rs232_bram.dcp

catch { report_utilization -file emiss_recep_rs232_bram_utilization_synth.rpt -pb emiss_recep_rs232_bram_utilization_synth.pb }
